spring:
  application:
    name: config-service

  cloud:
    config.server.git:
      uri: https://github.com/vivekkushwaha373/lovable-config-server
      username: vivekkushwaha373
      password: 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
      default-label: main

server.port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    config:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    discovery:
      enabled: false
    config.server.git:
      uri: https://github.com/vivekkushwaha373/lovable-config-server
      username: ${GIT_USERNAME}
      password: ${GIT_PASSWORD}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

