# k8s/stateful/minio.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: lovable-core
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
#          image: cgr.dev/chainguard/minio:latest
#            securityContext:
#              runAsUser: 0
#              runAsGroup: 0
#              allowPrivilegeEscalation: false
          image: vivkus/minio:latest
#          image: public.ecr.aws/r1l6m5k6/quay.io/minio/minio:RELEASE.2024-07-04T14-25-45Z
          args: [server, /data, --console-address, ":9001"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MINIO_ROOT_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: minio-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: lovable-core
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
    - name: console
      port: 9001